export const currencies = [
  { id: 'USD', name: 'US Dollar', symbol: '$' },
  { id: 'EUR', name: 'Euro', symbol: '€' },
  { id: 'GBP', name: 'British Pound', symbol: '£' },
  { id: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { id: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { id: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
  { id: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
  { id: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { id: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { id: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
  { id: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { id: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { id: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { id: 'MXN', name: 'Mexican Peso', symbol: '$' },
  { id: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
  { id: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
  { id: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { id: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { id: 'DKK', name: 'Danish Krone', symbol: 'kr' },
  { id: 'PLN', name: 'Polish Złoty', symbol: 'zł' },
];
